### PR TITLE
2D shapes tutorial

### PR DESCRIPTION
**Pull request by sethboyles**
Here's a start on the "Drawing 2D Shapes" tutorial.  It's not finished--I've covered drawing ellipses, rects, etc, but still have to cover drawing lines, polylines, and the `polygon` method.  I wanted to get some general feedback on the direction of this tutorial before I went ahead and finished writing it.  So let me know what you think, and if there should be anything else that the tutorial covers that I haven't mentioned.

### CODE REVIEW

**Comment by mitchmindtree** [comment]
@sethboyles this is perfect! I really love where this is going, the writing is concise, cohesive and friendly - I can't wait to read the rest :heart_eyes:

**Comment by sethboyles** [comment]
Great!  I'll keep going with it then.

**Comment by sethboyles** [comment]
yikes--the past 2 months were pretty busy, but I finally got this done.  I'm sure it could use a proofread.  Let me know what you think!

**Comment by JoshuaBatty** [comment]
@sethboyles this is fantastic. Thanks so much for putting this together! Just had a read over it and all looks good to me to merge in. @mitchmindtree anything you want changed or are we happy to merge this into the guide?

**Comment by mitchmindtree** [comment]
This is soooooooooo good! I'm happy to merge this as is for sure!

One thing that might be nice to add in a follow-up PR is to make sure all the code examples are tested via CI. This can be a bit finicky though as it normally means adding a bunch of other hidden code to ensure each of the snippets are correct as well. I'll try get around to this some day if noone beats me to it :)

Anyways thanks again @sethboyles, I'm sure many folks will find this very useful!

**Comment by sethboyles** [comment]
Great, thanks for the quick merge!  I agree about having the examples tested, it would help keep up to date with new nannou versions.  

By the way, if you decide to tweet this out from the nannou account, do you mind @ mentioning me?  http://twitter.com/sethbboyles.

Thanks!

**Comment by JoshuaBatty** [comment]
Thanks @sethboyles just credited you on a twitter post just then! :)

**Pull request merged**
