### PR TITLE
linked mitchmindtree sketches

### PR DESCRIPTION
**Pull request by tpltnt**
Hi there,

I added a link to the sketches by mitchmindtree.

Cheers,
tpltnt

### CODE REVIEW

**Comment by tpltnt** [comment]
rebased with master

**Comment by mitchmindtree** [comment]
Thanks @tpltnt,

Re rebase: It looks like you may not have rebased onto the latest master - if you check the diff many recent changes are removed.

I think when we add each showcase it would also be nice if we can include some pictures/animations and a small write-up, though I'm still unsure of how to best way to structure this section.

**Comment by tpltnt** [comment]
I rebased against the latest master (1d6d498ef241b8b92db8d8e9775544758d8f4bdb). The link is provisional to have (had) at least something to point to. Doing a proper showcase would warrant a separate PR.

**Comment by tpltnt** [comment]
ping

**Comment by tpltnt** [comment]
ping

**Comment by tpltnt** [comment]
What is blocks this PR from merging?

**Comment by mitchmindtree** [comment]
I am still hesitant to merge this as my sketches are not up to date and there are no pictures at the linked location, however I guess this is better than nothing until we can provide a proper structure for this section.

**Pull request merged**
